compatibility_date = "2021-10-19"
name = "postitmonster"
type = "javascript"
workers_dev = true

kv_namespaces = [
  {binding = "POSTS", preview_id = "id", id = "id"},
]

[build]
command = "yarn install && yarn build"
[build.upload]
format = "service-worker"

[vars]
PUBLIC_URL = "https://postit.monster"
API_URL = "https://api.postit.monster"
WORKER_URL="https://postitmonster.worker-api.workers.dev"
MODE = "production"

[env.development.vars]
PUBLIC_URL = "http://localhost:3000"
API_URL = "http://localhost:3001"
WORKER_URL="https://postitmonster.worker-api.workers.dev"
MODE = "dev"
