name = "postitmonster-auth"
type = "javascript"
workers_dev = true
compatibility_date = "2021-11-07"

kv_namespaces = [
    { binding = "AUTH", preview_id = "5d13fc5fafab453fbc8e7b63ac9e0fab", id = "0ab1f0d1e3e8495d95530e7d15d7a860" }
]

[build]
command = "cd wasm && cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir = "wasm/build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

[vars]
WORKERS_RS_VERSION = "0.0.7"
API_URL = "https://api.postit.monster"
MODE = "production"
PUBLIC_URL = "https://postit.monster"
WORKER_URL = "https://postitmonster.worker-api.workers.dev"

[env.development.vars]
WORKERS_RS_VERSION = "0.0.7"
API_URL = "http://localhost:3001"
MODE = "dev"
PUBLIC_URL = "http://localhost:3000"
WORKER_URL = "https://postitmonster.worker-api.workers.dev"
