// Code generated by qtc from "json.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line json.qtpl:1
package templates

//line json.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line json.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line json.qtpl:2
type MessageRes struct {
	Message string
}

// JSON marshaling

//line json.qtpl:9
func (d *MessageRes) StreamJSON(qw422016 *qt422016.Writer) {
//line json.qtpl:9
	qw422016.N().S(`{"message":`)
//line json.qtpl:11
	qw422016.N().S(d.Message)
//line json.qtpl:11
	qw422016.N().S(`,}`)
//line json.qtpl:13
}

//line json.qtpl:13
func (d *MessageRes) WriteJSON(qq422016 qtio422016.Writer) {
//line json.qtpl:13
	qw422016 := qt422016.AcquireWriter(qq422016)
//line json.qtpl:13
	d.StreamJSON(qw422016)
//line json.qtpl:13
	qt422016.ReleaseWriter(qw422016)
//line json.qtpl:13
}

//line json.qtpl:13
func (d *MessageRes) JSON() string {
//line json.qtpl:13
	qb422016 := qt422016.AcquireByteBuffer()
//line json.qtpl:13
	d.WriteJSON(qb422016)
//line json.qtpl:13
	qs422016 := string(qb422016.B)
//line json.qtpl:13
	qt422016.ReleaseByteBuffer(qb422016)
//line json.qtpl:13
	return qs422016
//line json.qtpl:13
}
